=== pieper/slicer2/Base/tcl/mrml20.dtd
<!ELEMENT MRML (Transform | Volume | Model | Color | Options)*>

<!ELEMENT Transform (Transform | Matrix | Volume | Model)*>

<!ELEMENT Matrix (#PCDATA)>
<!ATTLIST Matrix 
    name NMTOKEN "Matrix"
    description CDATA ""
    matrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1">

<!ELEMENT Volume (#PCDATA)>
<!ATTLIST Volume 
    name NMTOKEN ""
    filePattern CDATA "s.03d"
    filePrefix CDATA #REQUIRED
    rasToIjkMatrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1"
    rasToVtkMatrix NMTOKENS "1 0 0 0  0 -1 0 0  0 0 1 0  0 0 0 1"
    colorLUT NMTOKEN ""
    description CDATA ""
    scalarType (Char | UnsignedChar | Short | UnsignedShort | Int | UnsignedInt | Long | UnsignedLong | Float | Double) "Short"
    numScalars NMTOKEN "1"
    littleEndian (1 | 0) "0"
    interpolate (1 | 0) "0"
    labelMap (1 | 0) "0"
    tilt NMTOKEN "0.0"
    autoWindowLevel (1 | 0) "1"
    window CDATA "127"
    level CDATA "64"
    autoThreshold (0 | 1) "0"
    lowerThreshold CDATA "-32768"
    upperThreshold CDATA "32767"
    ignore (1 | 0) "0"
    imageRange NMTOKENS "1 1"
    dimensions NMTOKENS "256 256"
    spacing NMTOKENS "1 1 1"
    scanOrder (LR | RL | SI | IS | AP | PA | OB) "SI"
    positionMatrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1">

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model 
    name NMTOKEN ""
    fileName CDATA  #REQUIRED
    color NMTOKEN ""
    description CDATA ""
    opacity NMTOKEN "1.0"
    visibility (1 | 0) "1"
    clipping (1 | 0) "0"
    backfaceCulling (1 | 0) "1"
    scalarVisibility (1 | 0) "0"
    ignore (1 | 0) "0"
    scalarRange NMTOKENS "0 100">

<!ELEMENT Color (#PCDATA)>
<!ATTLIST Color 
    name NMTOKEN #REQUIRED
    description CDATA ""
    diffuseColor NMTOKENS "1.0 1.0 1.0"
    ambient NMTOKEN "0.0"
    diffuse NMTOKEN "1.0"
    specular NMTOKEN "0.0"
    power NMTOKEN "1"
    labels NMTOKEN "">

<!ELEMENT Options (#PCDATA)>
<!ATTLIST Options 
    program CDATA #REQUIRED
    content CDATA "">

=== pieper/slicer2/Modules/vtkFreeSurferReaders/tcl/ColorsFreesurfer.xml
<?xml version="1.0" standalone='no'?>
<!DOCTYPE MRML SYSTEM "mrml20.dtd">
<MRML>
<Color name='Unknown' diffuseColor='0 0 0' labels='0'></Color>
<Color name='Left-Cerebral-Exterior' diffuseColor='0.803922 0.243137 0.305882' labels='1'></Color>
<Color name='Left-Cerebral-White-Matter' diffuseColor='0.882353 0.882353 0.882353' labels='2'></Color>
<Color name='Left-Cerebral-Cortex' diffuseColor='0.803922 0.243137 0.305882' labels='3'></Color>
<Color name='Left-Lateral-Ventricle' diffuseColor='0.470588 0.0705882 0.52549' labels='4'></Color>
<Color name='Left-Inf-Lat-Vent' diffuseColor='0.768627 0.227451 0.980392' labels='5'></Color>
<Color name='Left-Cerebellum-Exterior' diffuseColor='0 0.580392 0' labels='6'></Color>
<Color name='Left-Cerebellum-White-Matter' diffuseColor='0.862745 0.972549 0.643137' labels='7'></Color>
<Color name='Left-Cerebellum-Cortex' diffuseColor='0.901961 0.580392 0.133333' labels='8'></Color>
<Color name='Left-Thalamus' diffuseColor='0 0.462745 0.054902' labels='9'></Color>
<Color name='Left-Thalamus-Proper' diffuseColor='0 0.462745 0.054902' labels='10'></Color>
<Color name='Left-Caudate' diffuseColor='0.478431 0.729412 0.862745' labels='11'></Color>
<Color name='Left-Putamen' diffuseColor='0.92549 0.0509804 0.690196' labels='12'></Color>
<Color name='Left-Pallidum' diffuseColor='0.0470588 0.188235 1' labels='13'></Color>
<Color name='3rd-Ventricle' diffuseColor='0.8 0.713725 0.556863' labels='14'></Color>
<Color name='4th-Ventricle' diffuseColor='0.164706 0.8 0.643137' labels='15'></Color>
<Color name='Brain-Stem' diffuseColor='0.466667 0.623529 0.690196' labels='16'></Color>
<Color name='Left-Hippocampus' diffuseColor='0.862745 0.847059 0.0784314' labels='17'></Color>
<Color name='Left-Amygdala' diffuseColor='0.403922 1 1' labels='18'></Color>
<Color name='Left-Insula' diffuseColor='0.313725 0.768627 0.384314' labels='19'></Color>
<Color name='Left-Operculum' diffuseColor='0.235294 0.227451 0.823529' labels='20'></Color>
<Color name='Line-1' diffuseColor='0.235294 0.227451 0.823529' labels='21'></Color>
<Color name='Line-2' diffuseColor='0.235294 0.227451 0.823529' labels='22'></Color>
<Color name='Line-3' diffuseColor='0.235294 0.227451 0.823529' labels='23'></Color>
<Color name='CSF' diffuseColor='0.235294 0.235294 0.235294' labels='24'></Color>
<Color name='Left-Lesion' diffuseColor='1 0.647059 0' labels='25'></Color>
<Color name='Left-Accumbens-area' diffuseColor='1 0.647059 0' labels='26'></Color>
<Color name='Left-Substancia-Nigra' diffuseColor='0 1 0.498039' labels='27'></Color>
<Color name='Left-VentralDC' diffuseColor='0.647059 0.164706 0.164706' labels='28'></Color>
<Color name='Left-undetermined' diffuseColor='0.529412 0.807843 0.921569' labels='29'></Color>
<Color name='Left-vessel' diffuseColor='0.627451 0.12549 0.941176' labels='30'></Color>
<Color name='Left-choroid-plexus' diffuseColor='0 1 1' labels='31'></Color>
<Color name='Left-F3orb' diffuseColor='0.392157 0.196078 0.392157' labels='32'></Color>
<Color name='Left-lOg' diffuseColor='0.529412 0.196078 0.290196' labels='33'></Color>
<Color name='Left-aOg' diffuseColor='0.478431 0.529412 0.196078' labels='34'></Color>
<Color name='Left-mOg' diffuseColor='0.2 0.196078 0.529412' labels='35'></Color>
<Color name='Left-pOg' diffuseColor='0.290196 0.607843 0.235294' labels='36'></Color>
<Color name='Left-Stellate' diffuseColor='0.470588 0.243137 0.168627' labels='37'></Color>
<Color name='Left-Porg' diffuseColor='0.290196 0.607843 0.235294' labels='38'></Color>
<Color name='Left-Aorg' diffuseColor='0.478431 0.529412 0.196078' labels='39'></Color>
<Color name='Right-Cerebral-Exterior' diffuseColor='0.803922 0.243137 0.305882' labels='40'></Color>
<Color name='Right-Cerebral-White-Matter' diffuseColor='0 0.882353 0' labels='41'></Color>
<Color name='Right-Cerebral-Cortex' diffuseColor='0.803922 0.243137 0.305882' labels='42'></Color>
<Color name='Right-Lateral-Ventricle' diffuseColor='0.470588 0.0705882 0.52549' labels='43'></Color>
<Color name='Right-Inf-Lat-Vent' diffuseColor='0.768627 0.227451 0.980392' labels='44'></Color>
<Color name='Right-Cerebellum-Exterior' diffuseColor='0 0.580392 0' labels='45'></Color>
<Color name='Right-Cerebellum-White-Matter' diffuseColor='0.862745 0.972549 0.643137' labels='46'></Color>
<Color name='Right-Cerebellum-Cortex' diffuseColor='0.901961 0.580392 0.133333' labels='47'></Color>
<Color name='Right-Thalamus' diffuseColor='0 0.462745 0.054902' labels='48'></Color>
<Color name='Right-Thalamus-Proper' diffuseColor='0 0.462745 0.054902' labels='49'></Color>
<Color name='Right-Caudate' diffuseColor='0.478431 0.729412 0.862745' labels='50'></Color>
<Color name='Right-Putamen' diffuseColor='0.92549 0.0509804 0.690196' labels='51'></Color>
<Color name='Right-Pallidum' diffuseColor='1 0.188235 1' labels='52'></Color>
<Color name='Right-Hippocampus' diffuseColor='0.862745 0.847059 0.0784314' labels='53'></Color>
<Color name='Right-Amygdala' diffuseColor='0.403922 1 1' labels='54'></Color>
<Color name='Right-Insula' diffuseColor='0.313725 0.768627 0.384314' labels='55'></Color>
<Color name='Right-Operculum' diffuseColor='0.235294 0.227451 0.823529' labels='56'></Color>
<Color name='Right-Lesion' diffuseColor='1 0.647059 0' labels='57'></Color>
<Color name='Right-Accumbens-area' diffuseColor='1 0.647059 0' labels='58'></Color>
<Color name='Right-Substancia-Nigra' diffuseColor='0 1 0.498039' labels='59'></Color>
<Color name='Right-VentralDC' diffuseColor='0.647059 0.164706 0.164706' labels='60'></Color>
<Color name='Right-undetermined' diffuseColor='0.529412 0.807843 0.921569' labels='61'></Color>
<Color name='Right-vessel' diffuseColor='0.627451 0.12549 0.941176' labels='62'></Color>
<Color name='Right-choroid-plexus' diffuseColor='0 1 1' labels='63'></Color>
<Color name='Right-F3orb' diffuseColor='0.392157 0.196078 0.392157' labels='64'></Color>
<Color name='Right-lOg' diffuseColor='0.529412 0.196078 0.290196' labels='65'></Color>
<Color name='Right-aOg' diffuseColor='0.478431 0.529412 0.196078' labels='66'></Color>
<Color name='Right-mOg' diffuseColor='0.2 0.196078 0.529412' labels='67'></Color>
<Color name='Right-pOg' diffuseColor='0.290196 0.607843 0.235294' labels='68'></Color>
<Color name='Right-Stellate' diffuseColor='0.470588 0.243137 0.168627' labels='69'></Color>
<Color name='Right-Porg' diffuseColor='0.290196 0.607843 0.235294' labels='70'></Color>
<Color name='Right-Aorg' diffuseColor='0.478431 0.529412 0.196078' labels='71'></Color>
<Color name='5th-Ventricle' diffuseColor='0.470588 0.745098 0.588235' labels='72'></Color>
<Color name='Right_Thin_Cerebral_White_Matter' diffuseColor='0.941176 0.941176 0.941176' labels='73'></Color>
<Color name='Left_Thin_Cerebral_White_Matter' diffuseColor='0.941176 0.941176 0.941176' labels='74'></Color>
<Color name='Bone' diffuseColor='0.392157 0.392157 0.392157' labels='80'></Color>
<Color name='Fat' diffuseColor='1 1 1' labels='81'></Color>
<Color name='Bright-Unknown' diffuseColor='0.392157 0.941176 0.941176' labels='82'></Color>
<Color name='Dark_Unknown' diffuseColor='0.0784314 0.392157 0.392157' labels='83'></Color>
<Color name='Corpus_Callosum' diffuseColor='0.980392 1 0.196078' labels='84'></Color>
</MRML>
